---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(ggplot2)
detach('package:dplyr')
library(dplyr)
library(tidytext)
library(sentimentr)

```

```{r}
punnoose <- read_csv('nikhil_p_whatsapp.csv', header = TRUE) %>% 
  select(datetime, sender, text) %>% 
  mutate(datetime = dmy_hms(datetime),
         date = date(datetime),
         day = lubridate::wday(date, label = TRUE, abbr = FALSE)) %>%
    dplyr::mutate(dialogue_split = get_sentences(text)) %$%
    sentiment_by(dialogue_split, list(sender,date)) %>% 
    mutate(norm_sentiment = ave_sentiment/word_count)

p <- read_csv('nikhil_p_whatsapp.csv', header = TRUE) 
```

```{r}
dates <- p %>% 
  select(datetime, sender, text) %>% 
  mutate(datetime = dmy_hms(datetime),
         date = date(datetime),
         day = lubridate::wday(date, label = TRUE, abbr = FALSE)) %>%
    dplyr::mutate(dialogue_split = get_sentences(text)) %$%
    sentiment_by(dialogue_split, list(sender,date)) %>% 
  arrange(-ave_sentiment) %>% 
  top_n(20) %>% 
  pull(date)
```

```{r}
p %>% 
  select(datetime, sender, text) %>% 
  mutate(datetime = dmy_hms(datetime),
         date = date(datetime)) %>% 
  filter(date %in% dates)
```

```{r}
pranathi %>% 
  mutate(day = lubridate::wday(date, label = TRUE, abbr = FALSE)) %>% 
  group_by(day, sender) %>% 
  summarize(avg = mean(ave_sentiment)) %>% 
  ggplot() + 
  geom_col(aes(x = day, y = avg, group = sender, fill = sender), position = 'dodge')
```

```{r}
punnoose %>% 
  mutate(day = lubridate::wday(date, label = TRUE, abbr = FALSE)) %>% 
  group_by(day, sender) %>% 
  summarize(n = sum(word_count)) %>% 
  ggplot() + 
  geom_col(aes(x = day, y = n, group = sender))
```

```{r}


punnoose %>% 
  ggplot() +
  geom_smooth(aes(x = date, y = norm_sentiment, group = sender, colour = sender), se = FALSE) +
  theme_minimal()
```

```{r}
didige <- read_csv('didige_whatsapp.csv', header = TRUE) %>% 
  select(datetime, sender, text) %>% 
  mutate(datetime = dmy_hms(datetime),
         date = date(datetime),
         day = lubridate::wday(date, label = TRUE, abbr = FALSE)) %>% 
  dplyr::mutate(dialogue_split = get_sentences(text)) %$%
  sentiment_by(dialogue_split, list(sender,date)) %>% 
    mutate(norm_sentiment = ave_sentiment/word_count)




didige %>%
  ggplot() +
  geom_smooth(aes(x = date, y = ave_sentiment, group = sender, colour = sender), se = FALSE) +
  theme_minimal()
```

```{r}
riddhima <- read_csv('riddhima_whatsapp.csv', header = TRUE) %>% 
  select(datetime, sender, text) %>% 
  mutate(datetime = dmy_hms(datetime),
         date = date(datetime),
         day = lubridate::wday(date, label = TRUE, abbr = FALSE)) %>%
    dplyr::mutate(dialogue_split = get_sentences(text)) %$%
    sentiment_by(dialogue_split, list(sender,date)) %>% 
    mutate(norm_sentiment = ave_sentiment/word_count)



riddhima %>%
  ggplot() +
  geom_smooth(aes(x = date, y = ave_sentiment, group = sender, colour = sender)) +
  theme_minimal()
```

```{r}
pranathi <- read_csv('pranathi_whatsapp.csv', header = TRUE) %>% 
  select(datetime, sender, text) %>% 
  mutate(datetime = dmy_hms(datetime),
         date = date(datetime),
         day = lubridate::wday(date, label = TRUE, abbr = FALSE)) %>%
    dplyr::mutate(dialogue_split = get_sentences(text)) %$%
    sentiment_by(dialogue_split, list(sender,date)) %>% 
    mutate(norm_sentiment = ave_sentiment/word_count)
```

```{r}
pranathi %>% 
  ggplot() +
  geom_smooth(aes(x = date, y = ave_sentiment, group = sender, colour = sender), span = 0.4, se = FALSE) +
  theme_minimal()
```

```{r}
all <- bind_rows(punnoose, riddhima, didige, pranathi)

ggplot() +
  geom_smooth(data = all %>% filter(sender == 'Sush'), aes(x = date, y = ave_sentiment), se = F, colour = 'red') +
  geom_smooth(data = all %>% filter(sender!= 'Sush'), aes(x = date, y = ave_sentiment), se = F)
```


```{r}
bind_rows(punnoose, riddhima, didige, pranathi)%>% 
  ggplot() +
  geom_smooth(aes(x = date, y = ave_sentiment, group = sender, colour = sender), se = F) +
  theme_minimal()
```

